mysql:
  username: root
  password: 123456
  host: 43.139.195.17
  port: 8686
  name: ginchat
  dns: root:123456@(43.139.195.17:8686)/ginchat?charset=utf8mb4&parseTime=True&loc=Local
redis:
    addr: "43.139.195.17:6333"
    password: ""
    DB: 0
    poolSize: 30
    minIdleConn: 30